2024-05-12 15:39:18,783 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn/assert_positive/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:18,798 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn/assert_positive_1/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:18,871 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_1/assert_positive/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:18,885 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_1/assert_positive_1/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:18,958 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_2/assert_positive/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:18,972 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_2/assert_positive_1/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,054 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_3/assert_positive/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,074 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_3/assert_positive_1/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,177 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_4/assert_positive/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,191 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_4/assert_positive_1/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,258 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_5/assert_positive/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,271 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_5/assert_positive_1/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,354 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_6/assert_positive/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,378 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_6/assert_positive_1/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,443 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_7/assert_positive/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,455 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_7/assert_positive_1/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,521 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_8/assert_positive/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,534 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_8/assert_positive_1/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,601 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_9/assert_positive/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,614 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_9/assert_positive_1/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,682 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_10/assert_positive/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,694 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_10/assert_positive_1/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,760 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_11/assert_positive/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,772 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_11/assert_positive_1/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,837 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_12/assert_positive/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,850 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_12/assert_positive_1/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,917 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_13/assert_positive/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,929 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_13/assert_positive_1/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:19,994 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_14/assert_positive/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:20,007 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_14/assert_positive_1/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:20,071 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_15/assert_positive/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:20,083 - ERROR - ==================================
Object was never used (type <class 'tensorflow.python.framework.ops.Operation'>):
<tf.Operation 'my_attn_15/assert_positive_1/assert_less/Assert/AssertGuard/Identity' type=Identity>
If you want to mark it as used call its "mark_used()" method.
It was originally created here:
  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 955, in assert_less
    return _binary_assert('<', 'assert_less', math_ops.less, np.less, x, y, data,  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/ops/check_ops.py", line 463, in _binary_assert
    with ops.name_scope(name, opname, [x, y, data]):  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 155, in error_handler
    del filtered_tb  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/dispatch.py", line 1260, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)  File "/home/ubuntu/.local/lib/python3.10/site-packages/tensorflow/python/util/tf_should_use.py", line 288, in wrapped
    return _add_should_use_warning(fn(*args, **kwargs),
==================================
2024-05-12 15:39:20,132 - DEBUG - Logits shape: Tensor("Shape_1:0", shape=(3,), dtype=int32)
2024-05-12 15:39:20,132 - DEBUG - Expected shape: Tensor("Const:0", shape=(3,), dtype=int32)
2024-05-12 15:39:20,136 - DEBUG - Logits shape before reshape: Tensor("Shape_2:0", shape=(3,), dtype=int32)
2024-05-12 15:39:20,136 - DEBUG - Labels shape before reshape: Tensor("Shape_3:0", shape=(3,), dtype=int32)
